name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Kodu Cek
      run: |
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.sha }}

    - name: Python ve Sistem Paketlerini Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git ccache libffi-dev libssl-dev libtool autoconf automake gettext zlib1g-dev libltdl-dev pkg-config openjdk-17-jdk zip unzip python3-pip python3-setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install "cython<3.0.0" buildozer

    - name: SDK Lisans Klasörünü Hazırla
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "\n24333735771d99dcd2263d239e0713700a7b2b57\n89330822745758060100d856419e609a24131121\n7a93463f0350b413a3a99edba758211091690e0b\n832544e9d38d0119a8f80c341825a0433e547374\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333735771d99dcd2263d239e0713700a7b2b57" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: APK Derle
      run: |
        buildozer -v android debug

    - name: APK Hazırla
      run: |
        mkdir -p output_apk
        cp bin/*.apk output_apk/ 2>/dev/null || true

    - name: APK Yukle
      uses: actions/upload-artifact@v4
      with:
        name: bist-app-apk
        path: output_apk/
